"""Stable public error codes for the hashline text protocol."""

E_BAD_SHAPE = "E_BAD_SHAPE"
E_BAD_REF = "E_BAD_REF"
E_STALE_ANCHOR = "E_STALE_ANCHOR"
E_OVERLAP = "E_OVERLAP"
E_INVALID_PATCH = "E_INVALID_PATCH"
E_BINARY = "E_BINARY"
E_PATH = "E_PATH"
E_PRECONDITION = "E_PRECONDITION"
E_WRITE = "E_WRITE"
E_LEGACY_SHAPE = "E_LEGACY_SHAPE"

ALL_ERROR_CODES = frozenset({
    E_BAD_SHAPE,
    E_BAD_REF,
    E_STALE_ANCHOR,
    E_OVERLAP,
    E_INVALID_PATCH,
    E_BINARY,
    E_PATH,
    E_PRECONDITION,
    E_WRITE,
    E_LEGACY_SHAPE,
})
